# Generated by Django 3.0.3 on 2020-02-26 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produto',
            table='produto',
        ),
    ]
