# Generated by Django 3.0.3 on 2020-02-26 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('produto', '0003_produto_tempo_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='nota',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
